# Generated by Django 3.1.4 on 2020-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
